#Название выбранного языка в папке lang
lang_file: ru-RU.yml

#Секция для настройки требований для создания гос-ва
need_to_create_country:

  #Секция для настройки требований в предметах
  items:

    #Нужно ли брать ресурсы за создание гос-ва
    enable: true

    #Путь к файлу в котором указанный предметы нужные для создания гос-ва
    item_config: settings/country/items.yml

  #Секция для настройки требований в монетах
  economy:

    #Нужно ли брать деньги за создание гос-ва
    enable: true

    #Сумма, за которую можно создать гос-во
    sum: 14780


#Секция для настройки требований для создания города
need_to_create_town:

  #Секция для настройки требований в предметах
  items:

    #Нужно ли брать ресурсы за создание города
    enable: true

    #Путь к файлу в котором указанный предметы нужные для создания города
    item_config: settings/country/items.yml

  #Секция для настройки требований в монетах
  economy:

    #Нужно ли брать деньги за создание города
    enable: true

    #Сумма, за которую можно создать города
    sum: 14780

